In [42]:
import numpy as np
import random

In [163]:
indi_size = 4 # 1 indivíduo -> 4 genes
popu_size = 6 # 1 populacao -> 6 indivíduos

def createPopulation(popu_size):
    chrom = np.random.randint(0,30, size=(popu_size,indi_size), dtype='int')
    return chrom

def evaluate(chrom):
    return (abs(chrom[0] + 2*chrom[1] + 3*chrom[2] + 4*chrom[3] - 30))

def fitness(f_obj):
    return (1/(1+f_obj))

def calcProb(ftss, total):
    return (ftss/total)

def calcCumProb(ftss,popu_size):
    cp = np.random.randint(0, size=(popu_size,), dtype='int')
    cp[0] = ftss[0]
    for i in range(1,popu_size):
        cp[i] = cp[i-1] + ftss[i]
    return cp

def rouletteWheel(popu_size):
    rw = np.random.random(popu_size,)
    return rw

def calcNewGeneration(chrom,rw,cumProb,popu_size): # rw = roulette wheel
    newchrom = np.zeros(shape=(6,4), dtype='int')
    for i in range(0,popu_size):
        for j in range(0,popu_size-1):
            if rw[i] > cumProb[j] and rw[i] < cumProb[j+1]:
                newchrom[i] = chrom[j+1]
                #print("troca:",i,"x",j+1)
            elif j==0 and rw[i] < cumProb[j]:
                #print("troca:",i,"x",0,"cond2")
                newchrom[i] = chrom[0]
    return newchrom

def crossOver(chrom,i,j,rnd):
    chrom[i][rnd:] = chrom[j][rnd:]
    
def mutation(chrom,position,value,popu_size):
    k = 1
    for i in range(0,popu_size):
        for j in range(0,4):
            if (k == position):
                chrom[i][j] = value
                return
            k += 1

In [166]:
chrom = createPopulation(popu_size)
print("====== I N I C I O ======")
print(chrom)
print("======-------------======")
interator_number = 1
while True:
    f_obj = np.zeros(shape=(popu_size,), dtype='int')
    fitss = np.zeros(shape=(popu_size,), dtype='float')
    fitss_total = 0
    for i in range(0,popu_size):
        f_obj[i] = evaluate(chrom[i])
        if(f_obj[i] == 0):
            print("!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",chrom[i])
        fitss[i] = fitness(f_obj[i])
        fitss_total += fitss[i]
    #print("f_obj:",f_obj)
    #print("fitss:",fitss)
    #print("fitss_total:",fitss_total)
    
    rnd = np.random.random(popu_size,)
    probChrMutation = np.zeros(shape=(popu_size,), dtype='float')
    probChrMutation_acm = np.zeros(shape=(popu_size,), dtype='float')
    for i in range(0,popu_size):
        probChrMutation[i] = calcProb(fitss[i],fitss_total)
        if (i==0):
            probChrMutation_acm[i] = probChrMutation[i]
        else:
            probChrMutation_acm[i] = probChrMutation_acm[i-1] + probChrMutation[i]
    
    #print("rnd_probMut:",rnd)
    #print("probChrMutation:",probChrMutation)
    #print("probChrMutation_acm:",probChrMutation_acm)
    
    newChrom = calcNewGeneration(chrom, rnd, probChrMutation_acm, popu_size)
    chrom = newChrom
    
    #print("bf_crossover:\n",chrom)
    
    rnd = np.random.random(popu_size,)
    for i in range(0,popu_size):
        if rnd[i] < 0.25:
            k = i+1
            if i>5:
                k = 0
            while(k < 6):
                if rnd[k] < 0.25:
                    crossOver(chrom,i,k,random.randint(1,3))
                    break
                k += 1
                if k == 6:
                    k = 0
    
    #print(rnd)
    #print("af_crossover:\n", chrom)
    
    total_gen = indi_size*popu_size
    mutation_rate = 0.25 # 10%

    for i in range(0,int(total_gen * mutation_rate)):
        position = random.randint(0,total_gen)
        mutation(chrom,position,random.randint(0,30),popu_size)
    
    print(chrom)
    print("================================")
    interator_number += 1
    if(interator_number > 100):
        break
print("======  F I N A L ======")
print(chrom)
for i in range(0,popu_size):
    print(evaluate(chrom[i]))


====== I N I C I O ======
[[ 7 21  9 15]
 [ 6 10 11 26]
 [29 21 25 22]
 [18 28 27 24]
 [28 18 19  7]
 [11 21 19  1]]
======-------------======
[[11 21 19  1]
 [ 6 10 11 27]
 [28 18 19  7]
 [28 18 19 18]
 [18 28 19 24]
 [ 7 21  3 15]]
[[28 18 19 18]
 [11 21 19  2]
 [11 21 19 23]
 [ 7 21  3 15]
 [ 7 21  3 26]
 [28 18 15 18]]
[[24 21  3 15]
 [ 7 21  3  3]
 [11 21 19 23]
 [ 7 21  4 15]
 [28 18 19 18]
 [22 21  3  2]]
[[ 7 21  3  3]
 [14 21 24 23]
 [ 7 21  3  2]
 [ 7 21  3  2]
 [11 21 19 30]
 [22  8  3  2]]
[[17  8  3  2]
 [13 21  3  2]
 [29 17  3  2]
 [22  8  3  2]
 [ 7 21 24 16]
 [ 7 21  3  2]]
[[17  8  3 11]
 [13 21  3  2]
 [18 17  3  2]
 [28 21  2  2]
 [22  8  3  2]
 [ 7 21  3  2]]
[[ 7 21  2  2]
 [27 21  3  2]
 [26 21  2  2]
 [13 21  2  2]
 [18 17  6  2]
 [28 30 23  2]]
[[ 9 19  2  5]
 [13 21  3  2]
 [27 21 13  2]
 [13 21  2  2]
 [26 21  2  5]
 [13 21  2  2]]
[[26 21  2  5]
 [13 21  3  2]
 [13 21 16  2]
 [29 21  3 30]
 [13 21  4  2]
 [23 21 13 22]]
[[26 21  2  5]
 [13 21 23  2]
 [11 21 

In [3]:
cr = np.zeros(shape=(6,4), dtype='int')
cr[0] = [12,5,23,8]
cr[1] = [2,21,18,3]
cr[2] = [10,4,13,14]
cr[3] = [20,1,10,6]
cr[4] = [1,4,13,19]
cr[5] = [20,5,17,1]

f_obj = np.zeros(shape=(6,), dtype='int')
fitss = np.zeros(shape=(6,), dtype='float')
fitss_total = 0
for i in range(0,6):
    f_obj[i] = evaluate(cr[i])
    fitss[i] = selection(f_obj[i])
    fitss_total += fitss[i]

In [4]:
rnd = np.zeros(shape=(6,), dtype='float')
rnd = [0.201,0.284,0.099,0.822,0.398,0.501]
#rnd = np.random.randint(0,1 size=(6,))
probcr = np.zeros(shape=(6,), dtype='float')
probcr_acm = np.zeros(shape=(6,), dtype='float')
for i in range(0,6):
    probcr[i] = calcProb(fitss[i],fitss_total)
    if (i==0):
        probcr_acm[i] = probcr[i]
    else:
        probcr_acm[i] = probcr_acm[i-1] + probcr[i]
        
newcr = calcNewGeneration(cr, rnd, probcr_acm, 6)
print(newcr)

[[ 2 21 18  3]
 [10  4 13 14]
 [12  5 23  8]
 [20  5 17  1]
 [10  4 13 14]
 [20  1 10  6]]


In [5]:
rnd = [0.191,0.259,0.760,0.006,0.159,0.340]
for i in range(0,6):
    if rnd[i] < 0.25:
        k = i+1
        if i>5:
            k = 0
        while(k < 6):
            if rnd[k] < 0.25:
                crossOver(newcr,i,k,random.randint(1,3))
                break
            k += 1
            if k == 6:
                k = 0
print(newcr)

0 x 3   2
[ 2 21 18  3] [20  5 17  1]
[ 2 21 17  1] [20  5 17  1]
--------------
3 x 4   2
[20  5 17  1] [10  4 13 14]
[20  5 13 14] [10  4 13 14]
--------------
4 x 0   3
[10  4 13 14] [ 2 21 17  1]
[10  4 13  1] [ 2 21 17  1]
--------------
[[ 2 21 17  1]
 [10  4 13 14]
 [12  5 23  8]
 [20  5 13 14]
 [10  4 13  1]
 [20  1 10  6]]


In [22]:
total_gen = 24
mutation_rate = 0.1 # 10%

for i in range(0,int(total_gen * mutation_rate)):
    position = random.randint(0,24)
    mutation(total_gen,position,random.randint(0,24))

17 22
8 13
