In [115]:
import numpy as np
import random

In [134]:
def createPopulation(popsize):
    cr = np.random.randint(0,30, size=(popsize,4), dtype='int')
    return cr

def evaluate(cr):
    return (abs(cr[0] + 2*cr[1] + 3*cr[2] + 4*cr[3] - 30))

def selection(f_obj):
    return (1/(1+f_obj))

def calcProb(ftss, total):
    return (ftss/total)

def calcCumProb(ftss,popsize):
    cp = np.random.randint(0, size=(popsize,), dtype='int')
    cp[0] = ftss[0]
    for i in range(1,popsize):
        cp[i] = cp[i-1] + ftss[i]
    return cp

def routeWhell(popsize):
    rw = np.random.random(popsize,)
    return rw

def calcNewGeneration(cr,rw,cp,popsize):
    newcr = np.zeros(shape=(6,4), dtype='int')
    for i in range(0,popsize):
        for j in range(0,popsize-1):
            if rw[i] > cp[j] and rw[i] < cp[j+1]:
                newcr[i] = cr[j+1]
            elif j==0:
                newcr[i] = cr[j]
    return newcr

def crossOver(cr,i,j,rnd):
    print(i,"x",j," ",rnd)
    print(cr[i],cr[j])
    cr[i][rnd:] = cr[j][rnd:]
    print(cr[i],cr[j])
    print("--------------")

In [122]:
cr = np.zeros(shape=(6,4), dtype='int')
cr[0] = [12,5,23,8]
cr[1] = [2,21,18,3]
cr[2] = [10,4,13,14]
cr[3] = [20,1,10,6]
cr[4] = [1,4,13,19]
cr[5] = [20,5,17,1]

f_obj = np.zeros(shape=(6,), dtype='int')
fitss = np.zeros(shape=(6,), dtype='float')
fitss_total = 0
for i in range(0,6):
    f_obj[i] = evaluate(cr[i])
    fitss[i] = selection(f_obj[i])
    fitss_total += fitss[i]

In [123]:
rnd = np.zeros(shape=(6,), dtype='float')
rnd = [0.201,0.284,0.099,0.822,0.398,0.501]
#rnd = np.random.randint(0,1 size=(6,))
probcr = np.zeros(shape=(6,), dtype='float')
probcr_acm = np.zeros(shape=(6,), dtype='float')
for i in range(0,6):
    probcr[i] = calcProb(fitss[i],fitss_total)
    if (i==0):
        probcr_acm[i] = probcr[i]
    else:
        probcr_acm[i] = probcr_acm[i-1] + probcr[i]
        
newcr = calcNewGeneration(cr, rnd, probcr_acm, 6)
print(newcr)

[[ 2 21 18  3]
 [10  4 13 14]
 [12  5 23  8]
 [20  5 17  1]
 [10  4 13 14]
 [20  1 10  6]]


In [135]:
rnd = [0.191,0.259,0.760,0.006,0.159,0.340]
for i in range(0,6):
    if rnd[i] < 0.25:
        k = i+1
        if i>5:
            k = 0
        while(k < 6):
            if rnd[k] < 0.25:
                crossOver(newcr,i,k,random.randint(1,3))
                break
            k += 1
            if k == 6:
                k = 0
print(newcr)

0 x 3   2
[ 2  5 17  1] [20  5 17 14]
[ 2  5 17 14] [20  5 17 14]
--------------
3 x 4   3
[20  5 17 14] [10 21 17  1]
[20  5 17  1] [10 21 17  1]
--------------
4 x 0   2
[10 21 17  1] [ 2  5 17 14]
[10 21 17 14] [ 2  5 17 14]
--------------
[[ 2  5 17 14]
 [10  4 13 14]
 [12  5 23  8]
 [20  5 17  1]
 [10 21 17 14]
 [20  1 10  6]]


In [112]:
a = np.random.randint(0,9, size=(4,), dtype='int')
b = np.random.randint(0,9, size=(4,), dtype='int')
print(a,b)
a[0:] = b[0:]
b[3] = 83
print(a,b)

[3 3 8 5] [0 2 1 5]
[0 2 1 5] [ 0  2  1 83]
